version: '3'
services:
  blue:
    container_name: blue
    image: ojy0929/hdmedi-c
#    expose:
#      - 8080
    ports:
      - 8081:8080
    environment:
      - TZ=Asia/Seoul
  green:
    container_name: green
    image: ojy0929/hdmedi-c
#    expose:
#      - 8080
    ports:
      - 8082:8080
    environment:
      - TZ=Asia/Seoul
